#!/usr/bin/env condor_submit
# Celery worker for OpenMP tasks.
# There should typically be just one OpenMP task running at a time.

accounting_group = ligo.dev.o2.cbc.pe.bayestar
accounting_group_user = leo.singer

universe = local
getenv = true
executable = /usr/bin/env
arguments = "gwcelery worker -c 1 -Q openmp -n gwcelery-openmp-worker -l info"

error = gwcelery-openmp-worker.err
log = gwcelery-openmp-worker.log
output = gwcelery-openmp-worker.out

on_exit_remove = false
queue
