#!/usr/bin/env condor_submit
# Celery worker for normal tasks.

accounting_group = ligo.prod.o2.cbc.pe.bayestar
accounting_group_user = leo.singer

universe = local
getenv = true
executable = /usr/bin/env
arguments = "gwcelery worker --queues celery --hostname gwcelery-celery-worker --beat --loglevel=info"

error = gwcelery-celery-worker.err
log = gwcelery-celery-worker.log
output = gwcelery-celery-worker.out

on_exit_remove = false
queue
